#ifndef AEQUUS_VIDEO_ENUM_HPP
#define AEQUUS_VIDEO_ENUM_HPP
#include "../sdl_headers.hpp"
enum BlendMode {
  NONE = SDL_BLENDMODE_NONE,
  BLEND = SDL_BLENDMODE_BLEND,
  ADD = SDL_BLENDMODE_ADD,
  MOD = SDL_BLENDMODE_MOD
};
enum TextRenderer { TEXT_SOLID, TEXT_SHADED, TEXT_BLEND };
enum ButtonState { NORMAL, HOVER, PRESS, RELEASE };
enum Cases { CLIP, COLOR, CUSTOM, NOCASE };
enum FontOptions {
  THIN,
  ITALIC_THIN,
  EXTRA_LIGHT,
  ITALIC_EXTRA_LIGHT,
  LIGHT,
  ITALIC_LIGHT,
  REGULAR,
  ITALIC_REGULAR,
  MEDIUM,
  ITALIC_MEDIUM,
  SEMIBOLD,
  ITALIC_SEMIBOLD,
  BOLD,
  ITALIC_BOLD,
  EXTRA_BOLD,
  ITALIC_EXTRA_BOLD,
  BLACK,
  ITALIC_BLACK
};
enum LayoutFormat { HORIZONTAL, VERTICAL };
#endif
